const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const User = require('../models/User');
const Workout = require('../models/Workout');
const Exercise = require('../models/Exercise');
const WorkoutExercise = require('../models/WorkoutExercise');

const user_data = [
  { firstName: "John", lastName: "Baker", email: "aksjhad1@teste.pt", password: "hashed_password_1" },
  { firstName: "Max", lastName: "Butler", email: "aksjhad2@teste.pt", password: "hashed_password_2" },
  { firstName: "Ryan", lastName: "Fisher", email: "aksjhad3@teste.pt", password: "hashed_password_3" },
  { firstName: "Robert", lastName: "Gray", email: "aksjhad4@teste.pt", password: "hashed_password_4" },
  { firstName: "Sam", lastName: "Lewis", email: "aksjhad5@teste.pt", password: "hashed_password_5" },
  { firstName: "Alice", lastName: "Smith", email: "alice.s@teste.pt", password: "hashed_password_6" },
  { firstName: "David", lastName: "Miller", email: "d.miller@teste.pt", password: "hashed_password_7" },
  { firstName: "Emma", lastName: "Wilson", email: "emma.w@teste.pt", password: "hashed_password_8" },
  { firstName: "Lucas", lastName: "Brown", email: "l.brown@teste.pt", password: "hashed_password_9" },
  { firstName: "Sophia", lastName: "Davis", email: "sophia.d@teste.pt", password: "hashed_password_10" },
  { firstName: "James", lastName: "Garcia", email: "j.garcia@teste.pt", password: "hashed_password_11" },
  { firstName: "Olivia", lastName: "Martinez", email: "o.martinez@teste.pt", password: "hashed_password_12" },
  { firstName: "Daniel", lastName: "Hernandez", email: "d.hernandez@teste.pt", password: "hashed_password_13" },
  { firstName: "Isabella", lastName: "Lopez", email: "i.lopez@teste.pt", password: "hashed_password_14" },
  { firstName: "Matthew", lastName: "Gonzalez", email: "m.gonzalez@teste.pt", password: "hashed_password_15" },
  { firstName: "Mia", lastName: "Wilson", email: "m.wilson@teste.pt", password: "hashed_password_16" },
  { firstName: "Ethan", lastName: "Anderson", email: "e.anderson@teste.pt", password: "hashed_password_17" },
  { firstName: "Charlotte", lastName: "Thomas", email: "c.thomas@teste.pt", password: "hashed_password_18" },
  { firstName: "Alexander", lastName: "Taylor", email: "a.taylor@teste.pt", password: "hashed_password_19" },
  { firstName: "Amelia", lastName: "Moore", email: "a.moore@teste.pt", password: "hashed_password_20" },
  { firstName: "Michael", lastName: "Jackson", email: "m.jackson@teste.pt", password: "hashed_password_21" },
  { firstName: "Emily", lastName: "White", email: "e.white@teste.pt", password: "hashed_password_22" },
  { firstName: "Benjamin", lastName: "Harris", email: "b.harris@teste.pt", password: "hashed_password_23" },
  { firstName: "Harper", lastName: "Martin", email: "h.martin@teste.pt", password: "hashed_password_24" },
  { firstName: "William", lastName: "Thompson", email: "w.thompson@teste.pt", password: "hashed_password_25" },
  { firstName: "Evelyn", lastName: "Garcia", email: "e.garcia2@teste.pt", password: "hashed_password_26" },
  { firstName: "Sebastian", lastName: "Martinez", email: "s.martinez2@teste.pt", password: "hashed_password_27" },
  { firstName: "Abigail", lastName: "Robinson", email: "a.robinson@teste.pt", password: "hashed_password_28" },
  { firstName: "Jack", lastName: "Clark", email: "j.clark@teste.pt", password: "hashed_password_29" },
  { firstName: "Luna", lastName: "Rodriguez", email: "l.rodriguez@teste.pt", password: "hashed_password_30" }
];

const workout_data = [
  { "id": 1, "title": "Alpha Push", "description": "Heavy chest focus", "visibility": "public", "UserId": 1 },
  { "id": 2, "title": "Beta Pull", "description": "Back thickness routine", "visibility": "private", "UserId": 1 },
  { "id": 3, "title": "Leg Destruction", "description": "Quad dominant day", "visibility": "public", "UserId": 1 },
  { "id": 4, "title": "Quick HIIT", "description": "15 min fat burn", "visibility": "public", "UserId": 2 },
  { "id": 5, "title": "Upper Body Pump", "description": "High volume upper", "visibility": "private", "UserId": 2 },
  { "id": 6, "title": "Powerlifting Intro", "description": "SBD technical work", "visibility": "public", "UserId": 3 },
  { "id": 7, "title": "Ryan's Secret", "description": "Custom strength mix", "visibility": "private", "UserId": 3 },
  { "id": 8, "title": "Full Body A", "description": "Compound movements", "visibility": "public", "UserId": 4 },
  { "id": 9, "title": "Full Body B", "description": "Isolation movements", "visibility": "private", "UserId": 4 },
  { "id": 10, "title": "Core Master", "description": "Abs and lower back", "visibility": "public", "UserId": 5 },
  { "id": 11, "title": "Morning Flow", "description": "Yoga and mobility", "visibility": "public", "UserId": 6 },
  { "id": 12, "title": "Sprinting Prep", "description": "Explosive leg work", "visibility": "private", "UserId": 6 },
  { "id": 13, "title": "Olympic Clean", "description": "Technique focus", "visibility": "public", "UserId": 7 },
  { "id": 14, "title": "Bench Press Day", "description": "Chest and Triceps", "visibility": "public", "UserId": 8 },
  { "id": 15, "title": "Back & Biceps", "description": "Classic pull day", "visibility": "private", "UserId": 9 },
  { "id": 16, "title": "Glute Burner", "description": "Lower body isolation", "visibility": "public", "UserId": 10 },
  { "id": 17, "title": "Arm Farm", "description": "Bicep and Tricep supersets", "visibility": "public", "UserId": 11 },
  { "id": 18, "title": "Iron Shoulders", "description": "Deltoid focus", "visibility": "private", "UserId": 12 },
  { "id": 19, "title": "Swimming Dryland", "description": "Lat and core endurance", "visibility": "public", "UserId": 13 },
  { "id": 20, "title": "Calisthenics Base", "description": "Bodyweight only", "visibility": "public", "UserId": 14 },
  { "id": 21, "title": "Kettlebell Madness", "description": "Full body KB flow", "visibility": "private", "UserId": 15 },
  { "id": 22, "title": "Strongman Intro", "description": "Heavy carries", "visibility": "public", "UserId": 16 },
  { "id": 23, "title": "Endurance Run", "description": "Low heart rate", "visibility": "public", "UserId": 17 },
  { "id": 24, "title": "Boxing Circuit", "description": "Bag work and jump rope", "visibility": "private", "UserId": 18 },
  { "id": 25, "title": "Posture Fix", "description": "Rear delt and rhomboids", "visibility": "public", "UserId": 19 },
  { "id": 26, "title": "Pre-Habilitation", "description": "Joint health", "visibility": "public", "UserId": 20 },
  { "id": 27, "title": "Hypertrophy Chest", "description": "Incline focus", "visibility": "private", "UserId": 21 },
  { "id": 28, "title": "Deadlift Focus", "description": "Posterior chain", "visibility": "public", "UserId": 22 },
  { "id": 29, "title": "TRX Full Body", "description": "Suspension training", "visibility": "public", "UserId": 23 },
  { "id": 30, "title": "Metabolic Finish", "description": "Conditioning", "visibility": "private", "UserId": 24 },
  { "id": 31, "title": "Dumbbell Only", "description": "Home gym friendly", "visibility": "public", "UserId": 25 },
  { "id": 32, "title": "Sandbag Training", "description": "Unstable loads", "visibility": "public", "UserId": 26 },
  { "id": 33, "title": "Climbing Prep", "description": "Forearm and grip", "visibility": "private", "UserId": 27 },
  { "id": 34, "title": "Rowing Cardio", "description": "Intervals", "visibility": "public", "UserId": 28 },
  { "id": 35, "title": "Weekend Warrior", "description": "Total body 60min", "visibility": "public", "UserId": 29 },
  { "id": 36, "title": "Abs of Steel", "description": "Core compression", "visibility": "private", "UserId": 30 },
  { "id": 37, "title": "Shoulder Health", "description": "Scapular mobility", "visibility": "public", "UserId": 1 },
  { "id": 38, "title": "Legs Volume", "description": "10x10 squats", "visibility": "public", "UserId": 2 },
  { "id": 39, "title": "Upper Push B", "description": "Overhead focus", "visibility": "private", "UserId": 3 },
  { "id": 40, "title": "Lower Pull B", "description": "Hamstring curls", "visibility": "public", "UserId": 4 },
  { "id": 41, "title": "Speed Bench", "description": "Dynamic effort", "visibility": "public", "UserId": 5 },
  { "id": 42, "title": "Pause Squats", "description": "Technical depth", "visibility": "private", "UserId": 6 },
  { "id": 43, "title": "Heavy Rows", "description": "Lat thickness", "visibility": "public", "UserId": 7 },
  { "id": 44, "title": "Farmer Walks", "description": "Grip and trap", "visibility": "public", "UserId": 8 },
  { "id": 45, "title": "Facepulls Master", "description": "Rear delt volume", "visibility": "private", "UserId": 9 },
  { "id": 46, "title": "Lunge City", "description": "Unilateral focus", "visibility": "public", "UserId": 10 },
  { "id": 47, "title": "Tricep Pump", "description": "Pushdowns and dips", "visibility": "public", "UserId": 11 },
  { "id": 48, "title": "Bicep Peak", "description": "Concentration curls", "visibility": "private", "UserId": 12 },
  { "id": 49, "title": "Calf Raise Routine", "description": "Staircase volume", "visibility": "public", "UserId": 13 },
  { "id": 50, "title": "Plank Variations", "description": "Static holds", "visibility": "public", "UserId": 14 },
  { "id": 51, "title": "Burpee Hell", "description": "Cardio spikes", "visibility": "private", "UserId": 15 },
  { "id": 52, "title": "Clean and Press", "description": "Total power", "visibility": "public", "UserId": 16 },
  { "id": 53, "title": "Pullup Pyramid", "description": "Volume building", "visibility": "public", "UserId": 17 },
  { "id": 54, "title": "Pushup Mix", "description": "Chest endurance", "visibility": "private", "UserId": 18 },
  { "id": 55, "title": "Mountain Climber", "description": "Fast core", "visibility": "public", "UserId": 19 },
  { "id": 56, "title": "Russian Twists", "description": "Oblique focus", "visibility": "public", "UserId": 20 },
  { "id": 57, "title": "Wall Sits", "description": "Leg isometric", "visibility": "private", "UserId": 21 },
  { "id": 58, "title": "Hip Thrust Day", "description": "Glute strength", "visibility": "public", "UserId": 22 },
  { "id": 59, "title": "Arnold Press Focus", "description": "Shoulder rotation", "visibility": "public", "UserId": 23 },
  { "id": 60, "title": "Skullcrushers", "description": "Tricep extension", "visibility": "private", "UserId": 24 },
  { "id": 61, "title": "Lateral Raise X", "description": "Side delt burn", "visibility": "public", "UserId": 25 },
  { "id": 62, "title": "Romanian Deadlift", "description": "Hinge work", "visibility": "public", "UserId": 26 },
  { "id": 63, "title": "Lat Pulldown Plus", "description": "Vertical pull", "visibility": "private", "UserId": 27 },
  { "id": 64, "title": "Incline Dumbbell", "description": "Upper pec", "visibility": "public", "UserId": 28 },
  { "id": 65, "title": "Hammer Curls", "description": "Forearm/Brachialis", "visibility": "public", "UserId": 29 },
  { "id": 66, "title": "Bulgarian Split", "description": "Painful legs", "visibility": "private", "UserId": 30 },
  { "id": 67, "title": "Cable Rows", "description": "Mid-back focus", "visibility": "public", "UserId": 1 },
  { "id": 68, "title": "Dips Weighted", "description": "Power triceps", "visibility": "public", "UserId": 2 },
  { "id": 69, "title": "Jump Rope Fun", "description": "Coordination", "visibility": "private", "UserId": 3 },
  { "id": 70, "title": "Step Ups", "description": "Glute and quad", "visibility": "public", "UserId": 4 },
  { "id": 71, "title": "Chin Ups", "description": "Lats and biceps", "visibility": "public", "UserId": 5 },
  { "id": 72, "title": "Sumo Squat", "description": "Adductor focus", "visibility": "private", "UserId": 6 },
  { "id": 73, "title": "Good Mornings", "description": "Hamstring/Lower back", "visibility": "public", "UserId": 7 },
  { "id": 74, "title": "Zottman Curls", "description": "Forearm rotation", "visibility": "public", "UserId": 8 },
  { "id": 75, "title": "Spider Curls", "description": "Bicep isolation", "visibility": "private", "UserId": 9 },
  { "id": 76, "title": "Pec Deck Fly", "description": "Chest stretch", "visibility": "public", "UserId": 10 },
  { "id": 77, "title": "Leg Press Heavy", "description": "Leg mass", "visibility": "public", "UserId": 11 },
  { "id": 78, "title": "T-Bar Rows", "description": "Old school back", "visibility": "private", "UserId": 12 },
  { "id": 79, "title": "Landmine Press", "description": "Shoulder stability", "visibility": "public", "UserId": 13 },
  { "id": 80, "title": "Hack Squat", "description": "Quad focus", "visibility": "public", "UserId": 14 },
  { "id": 81, "title": "Reverse Fly", "description": "Rear delt", "visibility": "private", "UserId": 15 },
  { "id": 82, "title": "Bent Over Row", "description": "Free weight back", "visibility": "public", "UserId": 16 },
  { "id": 83, "title": "Front Squat", "description": "Core and quads", "visibility": "public", "UserId": 17 },
  { "id": 84, "title": "Single Leg Deadlift", "description": "Balance", "visibility": "private", "UserId": 18 },
  { "id": 85, "title": "Barbell Shrugs", "description": "Traps", "visibility": "public", "UserId": 19 },
  { "id": 86, "title": "Sledgehammer Hits", "description": "Core power", "visibility": "public", "UserId": 20 },
  { "id": 87, "title": "Box Jumps", "description": "Plyometrics", "visibility": "private", "UserId": 21 },
  { "id": 88, "title": "Battle Ropes", "description": "Work capacity", "visibility": "public", "UserId": 22 },
  { "id": 89, "title": "Goblet Squats", "description": "Beginner friendly", "visibility": "public", "UserId": 23 },
  { "id": 90, "title": "Incline Pushups", "description": "Lower chest", "visibility": "private", "UserId": 24 },
  { "id": 91, "title": "Decline Bench", "description": "Lower pec power", "visibility": "public", "UserId": 25 },
  { "id": 92, "title": "Leg Extension", "description": "Quad isolation", "visibility": "public", "UserId": 26 },
  { "id": 93, "title": "Cable Crossover", "description": "Pec pump", "visibility": "private", "UserId": 27 },
  { "id": 94, "title": "Concentration Curl", "description": "Bicep peak", "visibility": "public", "UserId": 28 },
  { "id": 95, "title": "Diamond Pushups", "description": "Tricep focus", "visibility": "public", "UserId": 29 },
  { "id": 96, "title": "Dead Bug", "description": "Deep core", "visibility": "private", "UserId": 30 },
  { "id": 97, "title": "Bird Dog", "description": "Spinal stability", "visibility": "public", "UserId": 1 },
  { "id": 98, "title": "Bear Crawl", "description": "Functional crawl", "visibility": "public", "UserId": 2 },
  { "id": 99, "title": "Hollow Body Hold", "description": "Gymnastic core", "visibility": "private", "UserId": 3 },
  { "id": 100, "title": "Final Burnout", "description": "Full body finisher", "visibility": "public", "UserId": 4 }
];

const exercise_data = [
  { title: "Bench Press", description: "Supino plano com barra" },
  { title: "Squat", description: "Agachamento livre com barra" },
  { title: "Deadlift", description: "Peso morto convencional" },
  { title: "Pull-ups", description: "Elevações na barra fixa" },
  { title: "Overhead Press", description: "Press militar de ombros" },
  { title: "Barbell Row", description: "Remada com barra" },
  { title: "Lunges", description: "Afundos com halteres" },
  { title: "Plank", description: "Prancha abdominal isométrica" },
  { title: "Bicep Curls", description: "Flexão de braços com halteres" },
  { title: "Tricep Dips", description: "Fundos de tríceps" },
  { title: "Leg Press", description: "Prensa de pernas 45 graus" },
  { title: "Lateral Raises", description: "Elevações laterais para ombros" },
  { title: "Face Pulls", description: "Puxada para face com corda" },
  { title: "Leg Curls", description: "Flexão de pernas na máquina" },
  { title: "Calf Raises", description: "Elevação de gémeos em pé" },
  { title: "Push-ups", description: "Flexões de braços no solo" },
  { title: "Box Jumps", description: "Salto para a caixa" },
  { title: "Kettlebell Swing", description: "Balanço com kettlebell" },
  { title: "Burpees", description: "Salto com flexão rítmica" },
  { title: "Romanian Deadlift", description: "Peso morto romeno" },
  { title: "Lat Pulldown", description: "Puxada vertical na polia" },
  { title: "Incline DB Press", description: "Supino inclinado com halteres" },
  { title: "Hammer Curls", description: "Flexão martelo" },
  { title: "Skull Crushers", description: "Tríceps testa com barra EZ" },
  { title: "Russian Twists", description: "Rotação de tronco para abs" },
  { title: "Bulgarian Split Squat", description: "Agachamento búlgaro unilateral" },
  { title: "Chin-ups", description: "Elevações com pega supinada" },
  { title: "Mountain Climbers", description: "Movimento de escalador no solo" },
  { title: "Wall Sit", description: "Cadeira isométrica na parede" },
  { title: "Hip Thrust", description: "Elevação pélvica com carga" }
];

const workoutexercise_data = [
  { "sets": 4, "reps": 10, "WorkoutId": 1, "ExerciseId": 1 },
  { "sets": 3, "reps": 12, "WorkoutId": 1, "ExerciseId": 4 },
  { "sets": 3, "reps": 15, "WorkoutId": 1, "ExerciseId": 10 },
  { "sets": 5, "reps": 5, "WorkoutId": 2, "ExerciseId": 5 },
  { "sets": 4, "reps": 8, "WorkoutId": 2, "ExerciseId": 6 },
  { "sets": 4, "reps": 6, "WorkoutId": 3, "ExerciseId": 2 },
  { "sets": 3, "reps": 12, "WorkoutId": 3, "ExerciseId": 7 },
  { "sets": 4, "reps": 20, "WorkoutId": 4, "ExerciseId": 19 },
  { "sets": 4, "reps": 10, "WorkoutId": 4, "ExerciseId": 17 },
  { "sets": 3, "reps": 12, "WorkoutId": 5, "ExerciseId": 1 },
  { "sets": 3, "reps": 15, "WorkoutId": 5, "ExerciseId": 26 },
  { "sets": 5, "reps": 3, "WorkoutId": 6, "ExerciseId": 2 },
  { "sets": 3, "reps": 5, "WorkoutId": 6, "ExerciseId": 3 },
  { "sets": 1, "reps": 5, "WorkoutId": 7, "ExerciseId": 3 },
  { "sets": 3, "reps": 10, "WorkoutId": 8, "ExerciseId": 1 },
  { "sets": 3, "reps": 10, "WorkoutId": 8, "ExerciseId": 2 },
  { "sets": 4, "reps": 15, "WorkoutId": 9, "ExerciseId": 16 },
  { "sets": 3, "reps": 60, "WorkoutId": 10, "ExerciseId": 12 },
  { "sets": 3, "reps": 30, "WorkoutId": 11, "ExerciseId": 28 },
  { "sets": 5, "reps": 5, "WorkoutId": 12, "ExerciseId": 17 },
  { "sets": 5, "reps": 5, "WorkoutId": 13, "ExerciseId": 4 },
  { "sets": 4, "reps": 8, "WorkoutId": 14, "ExerciseId": 1 },
  { "sets": 4, "reps": 10, "WorkoutId": 15, "ExerciseId": 5 },
  { "sets": 4, "reps": 12, "WorkoutId": 16, "ExerciseId": 25 },
  { "sets": 3, "reps": 15, "WorkoutId": 17, "ExerciseId": 8 },
  { "sets": 3, "reps": 15, "WorkoutId": 17, "ExerciseId": 9 },
  { "sets": 4, "reps": 12, "WorkoutId": 18, "ExerciseId": 10 },
  { "sets": 3, "reps": 10, "WorkoutId": 19, "ExerciseId": 5 },
  { "sets": 5, "reps": 20, "WorkoutId": 20, "ExerciseId": 16 },
  { "sets": 4, "reps": 15, "WorkoutId": 21, "ExerciseId": 18 },
  { "sets": 3, "reps": 8, "WorkoutId": 22, "ExerciseId": 3 },
  { "sets": 3, "reps": 20, "WorkoutId": 23, "ExerciseId": 19 },
  { "sets": 3, "reps": 45, "WorkoutId": 24, "ExerciseId": 12 },
  { "sets": 4, "reps": 15, "WorkoutId": 25, "ExerciseId": 13 },
  { "sets": 3, "reps": 12, "WorkoutId": 26, "ExerciseId": 29 },
  { "sets": 4, "reps": 10, "WorkoutId": 27, "ExerciseId": 26 },
  { "sets": 4, "reps": 8, "WorkoutId": 28, "ExerciseId": 14 },
  { "sets": 3, "reps": 12, "WorkoutId": 29, "ExerciseId": 6 },
  { "sets": 5, "reps": 10, "WorkoutId": 30, "ExerciseId": 19 },
  { "sets": 3, "reps": 12, "WorkoutId": 31, "ExerciseId": 11 },
  { "sets": 4, "reps": 12, "WorkoutId": 32, "ExerciseId": 18 },
  { "sets": 4, "reps": 6, "WorkoutId": 33, "ExerciseId": 5 },
  { "sets": 3, "reps": 30, "WorkoutId": 34, "ExerciseId": 28 },
  { "sets": 3, "reps": 15, "WorkoutId": 35, "ExerciseId": 16 },
  { "sets": 4, "reps": 20, "WorkoutId": 36, "ExerciseId": 24 },
  { "sets": 3, "reps": 15, "WorkoutId": 37, "ExerciseId": 13 },
  { "sets": 10, "reps": 10, "WorkoutId": 38, "ExerciseId": 2 },
  { "sets": 4, "reps": 8, "WorkoutId": 39, "ExerciseId": 4 },
  { "sets": 3, "reps": 12, "WorkoutId": 40, "ExerciseId": 14 },
  { "sets": 8, "reps": 3, "WorkoutId": 41, "ExerciseId": 1 },
  { "sets": 5, "reps": 5, "WorkoutId": 42, "ExerciseId": 2 },
  { "sets": 4, "reps": 6, "WorkoutId": 43, "ExerciseId": 6 },
  { "sets": 3, "reps": 10, "WorkoutId": 44, "ExerciseId": 3 },
  { "sets": 5, "reps": 20, "WorkoutId": 45, "ExerciseId": 13 },
  { "sets": 3, "reps": 15, "WorkoutId": 46, "ExerciseId": 11 },
  { "sets": 4, "reps": 12, "WorkoutId": 47, "ExerciseId": 23 },
  { "sets": 3, "reps": 12, "WorkoutId": 48, "ExerciseId": 8 },
  { "sets": 4, "reps": 25, "WorkoutId": 49, "ExerciseId": 15 },
  { "sets": 5, "reps": 60, "WorkoutId": 50, "ExerciseId": 12 },
  { "sets": 5, "reps": 15, "WorkoutId": 51, "ExerciseId": 19 },
  { "sets": 3, "reps": 8, "WorkoutId": 52, "ExerciseId": 4 },
  { "sets": 5, "reps": 10, "WorkoutId": 53, "ExerciseId": 5 },
  { "sets": 10, "reps": 10, "WorkoutId": 54, "ExerciseId": 16 },
  { "sets": 3, "reps": 40, "WorkoutId": 55, "ExerciseId": 28 },
  { "sets": 3, "reps": 20, "WorkoutId": 56, "ExerciseId": 24 },
  { "sets": 3, "reps": 45, "WorkoutId": 57, "ExerciseId": 2 },
  { "sets": 4, "reps": 10, "WorkoutId": 58, "ExerciseId": 25 },
  { "sets": 4, "reps": 12, "WorkoutId": 59, "ExerciseId": 30 },
  { "sets": 3, "reps": 15, "WorkoutId": 60, "ExerciseId": 9 },
  { "sets": 5, "reps": 15, "WorkoutId": 61, "ExerciseId": 10 },
  { "sets": 4, "reps": 10, "WorkoutId": 62, "ExerciseId": 14 },
  { "sets": 3, "reps": 12, "WorkoutId": 63, "ExerciseId": 21 },
  { "sets": 4, "reps": 12, "WorkoutId": 64, "ExerciseId": 26 },
  { "sets": 3, "reps": 15, "WorkoutId": 65, "ExerciseId": 21 },
  { "sets": 4, "reps": 12, "WorkoutId": 66, "ExerciseId": 20 },
  { "sets": 3, "reps": 12, "WorkoutId": 67, "ExerciseId": 27 },
  { "sets": 4, "reps": 8, "WorkoutId": 68, "ExerciseId": 29 },
  { "sets": 5, "reps": 2, "WorkoutId": 69, "ExerciseId": 19 },
  { "sets": 3, "reps": 15, "WorkoutId": 70, "ExerciseId": 11 },
  { "sets": 4, "reps": 8, "WorkoutId": 71, "ExerciseId": 5 },
  { "sets": 3, "reps": 12, "WorkoutId": 72, "ExerciseId": 2 },
  { "sets": 3, "reps": 10, "WorkoutId": 73, "ExerciseId": 14 },
  { "sets": 3, "reps": 12, "WorkoutId": 74, "ExerciseId": 8 },
  { "sets": 3, "reps": 12, "WorkoutId": 75, "ExerciseId": 8 },
  { "sets": 3, "reps": 15, "WorkoutId": 76, "ExerciseId": 1 },
  { "sets": 4, "reps": 10, "WorkoutId": 77, "ExerciseId": 7 },
  { "sets": 4, "reps": 8, "WorkoutId": 78, "ExerciseId": 6 },
  { "sets": 3, "reps": 12, "WorkoutId": 79, "ExerciseId": 4 },
  { "sets": 4, "reps": 12, "WorkoutId": 80, "ExerciseId": 2 },
  { "sets": 4, "reps": 15, "WorkoutId": 81, "ExerciseId": 10 },
  { "sets": 3, "reps": 10, "WorkoutId": 82, "ExerciseId": 6 },
  { "sets": 5, "reps": 5, "WorkoutId": 83, "ExerciseId": 2 },
  { "sets": 3, "reps": 12, "WorkoutId": 84, "ExerciseId": 14 },
  { "sets": 3, "reps": 15, "WorkoutId": 85, "ExerciseId": 10 },
  { "sets": 3, "reps": 10, "WorkoutId": 86, "ExerciseId": 18 },
  { "sets": 5, "reps": 5, "WorkoutId": 87, "ExerciseId": 17 },
  { "sets": 4, "reps": 30, "WorkoutId": 88, "ExerciseId": 19 },
  { "sets": 3, "reps": 15, "WorkoutId": 89, "ExerciseId": 2 },
  { "sets": 4, "reps": 15, "WorkoutId": 90, "ExerciseId": 16 },
  { "sets": 4, "reps": 8, "WorkoutId": 91, "ExerciseId": 1 },
  { "sets": 3, "reps": 15, "WorkoutId": 92, "ExerciseId": 7 },
  { "sets": 3, "reps": 12, "WorkoutId": 93, "ExerciseId": 1 },
  { "sets": 3, "reps": 12, "WorkoutId": 94, "ExerciseId": 8 },
  { "sets": 4, "reps": 12, "WorkoutId": 95, "ExerciseId": 16 },
  { "sets": 3, "reps": 15, "WorkoutId": 96, "ExerciseId": 12 },
  { "sets": 3, "reps": 12, "WorkoutId": 97, "ExerciseId": 12 },
  { "sets": 3, "reps": 10, "WorkoutId": 98, "ExerciseId": 19 },
  { "sets": 3, "reps": 30, "WorkoutId": 99, "ExerciseId": 12 },
  { "sets": 4, "reps": 15, "WorkoutId": 100, "ExerciseId": 19 }
]

const runSeed = async () => {
    try {
        await sequelize.query('SET FOREIGN_KEY_CHECKS = 0');
        await sequelize.sync({ force: true });
        await sequelize.query('SET FOREIGN_KEY_CHECKS = 1');
        
        console.log("A inserir Utilizadores...");
        await User.bulkCreate(user_data, { validate: true });

        console.log("A inserir Exercícios...");
        await Exercise.bulkCreate(exercise_data, { validate: true });

        console.log("A inserir Treinos...");
        await Workout.bulkCreate(workout_data, { validate: true });

        console.log("A inserir Relações (WorkoutExercises)...");
        await WorkoutExercise.bulkCreate(workoutexercise_data, { validate: true });

        console.log("Seed concluído com sucesso! A base de dados está pronta.");
        process.exit(0);

    } catch (error) {
        console.error("Erro fatal durante o seed: ", error);
        process.exit(1);
    }
};

runSeed();