const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const Workout = require('../models/Workout');

const workout_data = [
  { "id": 1, "title": "Treino Power - John", "description": "Rotina focada em power para o utilizador John.", "UserId": 1 },
  { "id": 2, "title": "Treino Functional - Max", "description": "Rotina focada em functional para o utilizador Max.", "UserId": 2 },
  { "id": 3, "title": "Treino Strength - Ryan", "description": "Rotina focada em strength para o utilizador Ryan.", "UserId": 3 },
  { "id": 4, "title": "Treino Hypertrophy - Robert", "description": "Rotina focada em hypertrophy para o utilizador Robert.", "UserId": 4 },
  { "id": 5, "title": "Treino Cardio - Sam", "description": "Rotina focada em cardio para o utilizador Sam.", "UserId": 5 },
  { "id": 6, "title": "Treino Endurance - Alice", "description": "Rotina focada em endurance para o utilizador Alice.", "UserId": 6 },
  { "id": 7, "title": "Treino Mobility - David", "description": "Rotina focada em mobility para o utilizador David.", "UserId": 7 },
  { "id": 8, "title": "Treino Power - Emma", "description": "Rotina focada em power para o utilizador Emma.", "UserId": 8 },
  { "id": 9, "title": "Treino Functional - Lucas", "description": "Rotina focada em functional para o utilizador Lucas.", "UserId": 9 },
  { "id": 10, "title": "Treino Strength - Sophia", "description": "Rotina focada em strength para o utilizador Sophia.", "UserId": 10 },
  { "id": 11, "title": "Treino Hypertrophy - James", "description": "Rotina focada em hypertrophy para o utilizador James.", "UserId": 11 },
  { "id": 12, "title": "Treino Cardio - Olivia", "description": "Rotina focada em cardio para o utilizador Olivia.", "UserId": 12 },
  { "id": 13, "title": "Treino Endurance - Daniel", "description": "Rotina focada em endurance para o utilizador Daniel.", "UserId": 13 },
  { "id": 14, "title": "Treino Mobility - Isabella", "description": "Rotina focada em mobility para o utilizador Isabella.", "UserId": 14 },
  { "id": 15, "title": "Treino Power - Matthew", "description": "Rotina focada em power para o utilizador Matthew.", "UserId": 15 },
  { "id": 16, "title": "Treino Functional - Mia", "description": "Rotina focada em functional para o utilizador Mia.", "UserId": 16 },
  { "id": 17, "title": "Treino Strength - Ethan", "description": "Rotina focada em strength para o utilizador Ethan.", "UserId": 17 },
  { "id": 18, "title": "Treino Hypertrophy - Charlotte", "description": "Rotina focada em hypertrophy para o utilizador Charlotte.", "UserId": 18 },
  { "id": 19, "title": "Treino Cardio - Alexander", "description": "Rotina focada em cardio para o utilizador Alexander.", "UserId": 19 },
  { "id": 20, "title": "Treino Endurance - Amelia", "description": "Rotina focada em endurance para o utilizador Amelia.", "UserId": 20 },
  { "id": 21, "title": "Treino Mobility - Michael", "description": "Rotina focada em mobility para o utilizador Michael.", "UserId": 21 },
  { "id": 22, "title": "Treino Power - Emily", "description": "Rotina focada em power para o utilizador Emily.", "UserId": 22 },
  { "id": 23, "title": "Treino Functional - Benjamin", "description": "Rotina focada em functional para o utilizador Benjamin.", "UserId": 23 },
  { "id": 24, "title": "Treino Strength - Harper", "description": "Rotina focada em strength para o utilizador Harper.", "UserId": 24 },
  { "id": 25, "title": "Treino Hypertrophy - William", "description": "Rotina focada em hypertrophy para o utilizador William.", "UserId": 25 },
  { "id": 26, "title": "Treino Cardio - Evelyn", "description": "Rotina focada em cardio para o utilizador Evelyn.", "UserId": 26 },
  { "id": 27, "title": "Treino Endurance - Sebastian", "description": "Rotina focada em endurance para o utilizador Sebastian.", "UserId": 27 },
  { "id": 28, "title": "Treino Mobility - Abigail", "description": "Rotina focada em mobility para o utilizador Abigail.", "UserId": 28 },
  { "id": 29, "title": "Treino Power - Jack", "description": "Rotina focada em power para o utilizador Jack.", "UserId": 29 },
  { "id": 30, "title": "Treino Functional - Luna", "description": "Rotina focada em functional para o utilizador Luna.", "UserId": 30 },
  { "id": 31, "title": "Treino Strength - John", "description": "Rotina focada em strength para o utilizador John.", "UserId": 1 },
  { "id": 32, "title": "Treino Hypertrophy - Max", "description": "Rotina focada em hypertrophy para o utilizador Max.", "UserId": 2 },
  { "id": 33, "title": "Treino Cardio - Ryan", "description": "Rotina focada em cardio para o utilizador Ryan.", "UserId": 3 },
  { "id": 34, "title": "Treino Endurance - Robert", "description": "Rotina focada em endurance para o utilizador Robert.", "UserId": 4 },
  { "id": 35, "title": "Treino Mobility - Sam", "description": "Rotina focada em mobility para o utilizador Sam.", "UserId": 5 },
  { "id": 36, "title": "Treino Power - Alice", "description": "Rotina focada em power para o utilizador Alice.", "UserId": 6 },
  { "id": 37, "title": "Treino Functional - David", "description": "Rotina focada em functional para o utilizador David.", "UserId": 7 },
  { "id": 38, "title": "Treino Strength - Emma", "description": "Rotina focada em strength para o utilizador Emma.", "UserId": 8 },
  { "id": 39, "title": "Treino Hypertrophy - Lucas", "description": "Rotina focada em hypertrophy para o utilizador Lucas.", "UserId": 9 },
  { "id": 40, "title": "Treino Cardio - Sophia", "description": "Rotina focada em cardio para o utilizador Sophia.", "UserId": 10 },
  { "id": 41, "title": "Treino Endurance - James", "description": "Rotina focada em endurance para o utilizador James.", "UserId": 11 },
  { "id": 42, "title": "Treino Mobility - Olivia", "description": "Rotina focada em mobility para o utilizador Olivia.", "UserId": 12 },
  { "id": 43, "title": "Treino Power - Daniel", "description": "Rotina focada em power para o utilizador Daniel.", "UserId": 13 },
  { "id": 44, "title": "Treino Functional - Isabella", "description": "Rotina focada em functional para o utilizador Isabella.", "UserId": 14 },
  { "id": 45, "title": "Treino Strength - Matthew", "description": "Rotina focada em strength para o utilizador Matthew.", "UserId": 15 },
  { "id": 46, "title": "Treino Hypertrophy - Mia", "description": "Rotina focada em hypertrophy para o utilizador Mia.", "UserId": 16 },
  { "id": 47, "title": "Treino Cardio - Ethan", "description": "Rotina focada em cardio para o utilizador Ethan.", "UserId": 17 },
  { "id": 48, "title": "Treino Endurance - Charlotte", "description": "Rotina focada em endurance para o utilizador Charlotte.", "UserId": 18 },
  { "id": 49, "title": "Treino Mobility - Alexander", "description": "Rotina focada em mobility para o utilizador Alexander.", "UserId": 19 },
  { "id": 50, "title": "Treino Power - Amelia", "description": "Rotina focada em power para o utilizador Amelia.", "UserId": 20 },
  { "id": 51, "title": "Treino Functional - Michael", "description": "Rotina focada em functional para o utilizador Michael.", "UserId": 21 },
  { "id": 52, "title": "Treino Strength - Emily", "description": "Rotina focada em strength para o utilizador Emily.", "UserId": 22 },
  { "id": 53, "title": "Treino Hypertrophy - Benjamin", "description": "Rotina focada em hypertrophy para o utilizador Benjamin.", "UserId": 23 },
  { "id": 54, "title": "Treino Cardio - Harper", "description": "Rotina focada em cardio para o utilizador Harper.", "UserId": 24 },
  { "id": 55, "title": "Treino Endurance - William", "description": "Rotina focada em endurance para o utilizador William.", "UserId": 25 },
  { "id": 56, "title": "Treino Mobility - Evelyn", "description": "Rotina focada em mobility para o utilizador Evelyn.", "UserId": 26 },
  { "id": 57, "title": "Treino Power - Sebastian", "description": "Rotina focada em power para o utilizador Sebastian.", "UserId": 27 },
  { "id": 58, "title": "Treino Functional - Abigail", "description": "Rotina focada em functional para o utilizador Abigail.", "UserId": 28 },
  { "id": 59, "title": "Treino Strength - Jack", "description": "Rotina focada em strength para o utilizador Jack.", "UserId": 29 },
  { "id": 60, "title": "Treino Hypertrophy - Luna", "description": "Rotina focada em hypertrophy para o utilizador Luna.", "UserId": 30 },
  { "id": 61, "title": "Treino Cardio - John", "description": "Rotina focada em cardio para o utilizador John.", "UserId": 1 },
  { "id": 62, "title": "Treino Endurance - Max", "description": "Rotina focada em endurance para o utilizador Max.", "UserId": 2 },
  { "id": 63, "title": "Treino Mobility - Ryan", "description": "Rotina focada em mobility para o utilizador Ryan.", "UserId": 3 },
  { "id": 64, "title": "Treino Power - Robert", "description": "Rotina focada em power para o utilizador Robert.", "UserId": 4 },
  { "id": 65, "title": "Treino Functional - Sam", "description": "Rotina focada em functional para o utilizador Sam.", "UserId": 5 },
  { "id": 66, "title": "Treino Strength - Alice", "description": "Rotina focada em strength para o utilizador Alice.", "UserId": 6 },
  { "id": 67, "title": "Treino Hypertrophy - David", "description": "Rotina focada em hypertrophy para o utilizador David.", "UserId": 7 },
  { "id": 68, "title": "Treino Cardio - Emma", "description": "Rotina focada em cardio para o utilizador Emma.", "UserId": 8 },
  { "id": 69, "title": "Treino Endurance - Lucas", "description": "Rotina focada em endurance para o utilizador Lucas.", "UserId": 9 },
  { "id": 70, "title": "Treino Mobility - Sophia", "description": "Rotina focada em mobility para o utilizador Sophia.", "UserId": 10 },
  { "id": 71, "title": "Treino Power - James", "description": "Rotina focada em power para o utilizador James.", "UserId": 11 },
  { "id": 72, "title": "Treino Functional - Olivia", "description": "Rotina focada em functional para o utilizador Olivia.", "UserId": 12 },
  { "id": 73, "title": "Treino Strength - Daniel", "description": "Rotina focada em strength para o utilizador Daniel.", "UserId": 13 },
  { "id": 74, "title": "Treino Hypertrophy - Isabella", "description": "Rotina focada em hypertrophy para o utilizador Isabella.", "UserId": 14 },
  { "id": 75, "title": "Treino Cardio - Matthew", "description": "Rotina focada em cardio para o utilizador Matthew.", "UserId": 15 },
  { "id": 76, "title": "Treino Endurance - Mia", "description": "Rotina focada em endurance para o utilizador Mia.", "UserId": 16 },
  { "id": 77, "title": "Treino Mobility - Ethan", "description": "Rotina focada em mobility para o utilizador Ethan.", "UserId": 17 },
  { "id": 78, "title": "Treino Power - Charlotte", "description": "Rotina focada em power para o utilizador Charlotte.", "UserId": 18 },
  { "id": 79, "title": "Treino Functional - Alexander", "description": "Rotina focada em functional para o utilizador Alexander.", "UserId": 19 },
  { "id": 80, "title": "Treino Strength - Amelia", "description": "Rotina focada em strength para o utilizador Amelia.", "UserId": 20 },
  { "id": 81, "title": "Treino Hypertrophy - Michael", "description": "Rotina focada em hypertrophy para o utilizador Michael.", "UserId": 21 },
  { "id": 82, "title": "Treino Cardio - Emily", "description": "Rotina focada em cardio para o utilizador Emily.", "UserId": 22 },
  { "id": 83, "title": "Treino Endurance - Benjamin", "description": "Rotina focada em endurance para o utilizador Benjamin.", "UserId": 23 },
  { "id": 84, "title": "Treino Mobility - Harper", "description": "Rotina focada em mobility para o utilizador Harper.", "UserId": 24 },
  { "id": 85, "title": "Treino Power - William", "description": "Rotina focada em power para o utilizador William.", "UserId": 25 },
  { "id": 86, "title": "Treino Functional - Evelyn", "description": "Rotina focada em functional para o utilizador Evelyn.", "UserId": 26 },
  { "id": 87, "title": "Treino Strength - Sebastian", "description": "Rotina focada em strength para o utilizador Sebastian.", "UserId": 27 },
  { "id": 88, "title": "Treino Hypertrophy - Abigail", "description": "Rotina focada em hypertrophy para o utilizador Abigail.", "UserId": 28 },
  { "id": 89, "title": "Treino Cardio - Jack", "description": "Rotina focada em cardio para o utilizador Jack.", "UserId": 29 },
  { "id": 90, "title": "Treino Endurance - Luna", "description": "Rotina focada em endurance para o utilizador Luna.", "UserId": 30 },
  { "id": 91, "title": "Treino Mobility - John", "description": "Rotina focada em mobility para o utilizador John.", "UserId": 1 },
  { "id": 92, "title": "Treino Power - Max", "description": "Rotina focada em power para o utilizador Max.", "UserId": 2 },
  { "id": 93, "title": "Treino Functional - Ryan", "description": "Rotina focada em functional para o utilizador Ryan.", "UserId": 3 },
  { "id": 94, "title": "Treino Strength - Robert", "description": "Rotina focada em strength para o utilizador Robert.", "UserId": 4 },
  { "id": 95, "title": "Treino Hypertrophy - Sam", "description": "Rotina focada em hypertrophy para o utilizador Sam.", "UserId": 5 },
  { "id": 96, "title": "Treino Cardio - Alice", "description": "Rotina focada em cardio para o utilizador Alice.", "UserId": 6 },
  { "id": 97, "title": "Treino Endurance - David", "description": "Rotina focada em endurance para o utilizador David.", "UserId": 7 },
  { "id": 98, "title": "Treino Mobility - Emma", "description": "Rotina focada em mobility para o utilizador Emma.", "UserId": 8 },
  { "id": 99, "title": "Treino Power - Lucas", "description": "Rotina focada em power para o utilizador Lucas.", "UserId": 9 },
  { "id": 100, "title": "Treino Functional - Sophia", "description": "Rotina focada em functional para o utilizador Sophia.", "UserId": 10 }
]

sequelize.sync({ force: true }).then(() => {

    Workout.bulkCreate(workout_data, { validate: true }).then((result) => {
        console.log(result);
    }).catch((error) => {
        console.log(error);
    });

}).catch((error) => {
    console.error('Unable to create table : ', error);
});